#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
#
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := circle.cpp filled_rectangle.cpp line.cpp my_object.cpp rectangle.cpp window.cpp

# header files in this project
HEADERS := circle.hpp filled_rectangle.hpp line.hpp my_object.hpp rectangle.hpp window.hpp

# other places to look for files for this project
SEARCH  :=

# set RELATIVE to the next higher directory
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
